name: Sauce demo Web App Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
    # Runs the workflow every 1 hour
    # - cron: '0 */1 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate mochawesome report
        run: |
          npx mochawesome-merge cypress/results/*.json > cypress/results/report.json
          npx mochawesome-report-generator cypress/results/report.json
